version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    cooldown:
      semver-patch-days: 3
      semver-minor-days: 7
      semver-major-days: 14
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      types-dependencies:
        patterns:
          - "@types/*"
      inquirer:
        patterns:
          - "@inquirer/*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    cooldown:
      default-days: 3
    commit-message:
      prefix: "chore"
      include: "scope"
